### ISSUE TITLE
Migrate from clipboard.js

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#83]
Now that we have the appropriate permissions, we can remove clipboard.js and implement the standard Chrome clipboard API.

**Comment by connordeckers** [comment]
As it turns out, browsers currently don't really support clipboard modification. The current process involves adding an element to the DOM, programatically selecting it's content, executing a `copy` action, and then removing the DOM element. This is inefficient, and silly. For the time being, there's no harm in utilising the `Clipboard.js` library, and I think it would be more efficient to do so, until browsers provide a proper Clipboard API.
